//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bus
    {
        public int id_bus { get; set; }
        [Display(Name ="Marque")]
        public string nom { get; set; }
        [Display(Name ="Nb place")]
        public int nbr_place { get; set; }
        public bool climatiseur { get; set; }
        public bool tv { get; set; }
        public string description { get; set; }
        public int id_societe { get; set; }
        public int id_navette { get; set; }
        public string image { get; set; }
    
        public virtual Navette Navette { get; set; }
        public virtual Societe Societe { get; set; }
    }
}
