//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int id_bus { get; set; }
        public string nom { get; set; }
        public int nbr_place { get; set; }
        public bool climatiseur { get; set; }
        public bool tv { get; set; }
        public string description { get; set; }
        public int id_societe { get; set; }
        public int id_navette { get; set; }
        public string image { get; set; }
    
        public virtual Navette Navette { get; set; }
        public virtual Societe Societe { get; set; }
    }
}
