//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int id_demande { get; set; }
        public string depart { get; set; }
        public string arriver { get; set; }
        public System.DateTime date_depart { get; set; }
        public System.DateTime date_arriver { get; set; }
        public int id_client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
