//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int id_demande { get; set; }
        public string depart { get; set; }
        public string arriver { get; set; }
        public System.DateTime date_depart { get; set; }
        public System.DateTime date_arriver { get; set; }
        public int id_client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
