//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effectuer
    {
        public int id_client { get; set; }
        public int id_abonnement { get; set; }
        public Nullable<int> duree { get; set; }
    
        public virtual Abonnement Abonnement { get; set; }
        public virtual Client Client { get; set; }
    }
}
