//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effectuer
    {
        public int id_client { get; set; }
        public int id_abonnement { get; set; }
        public int duree { get; set; }
    
        public virtual Abonnement Abonnement { get; set; }
        public virtual Client Client { get; set; }
    }
}
