//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Navette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Navette()
        {
            this.Abonnements = new HashSet<Abonnement>();
            this.Buses = new HashSet<Bus>();
        }
    
        public int id_navette { get; set; }
        [Display(Name = "Lieu de depart")]
        public string lieu_depart { get; set; }
        [Display(Name = "Lieu d'arrivé")]
        public string lieu_arriver { get; set; }
        [Display(Name = "Heure de depart")]
        [DataType(DataType.Time)]
        public System.DateTime date_depart { get; set; }
        [Display(Name = "Heure d'arrivée")]
        [DataType(DataType.Time)]
        public System.DateTime date_arriver { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Buses { get; set; }
    }
}
